public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int i = 3;
        byte b = 2;
        short s = 100;
        long l = 100000;
        float f = 1.5f;
        double d = 2.501;
        System.out.println("Значение переменной i с типом int равно " + i);
        System.out.println("Значение переменной b с типом byte равно " + b);
        System.out.println("Значение переменной s с типом short равно " + s);
        System.out.println("Значение переменной l с типом long равно " + l);
        System.out.println("Значение переменной f с типом float равно " + f);
        System.out.println("Значение переменной d с типом double равно " + d);
        System.out.println("Задача 2");
        int i_1 = -159;
        byte b_1 = 67;
        short s_1 = 27897;
        long l_1 = 987678965549L;
        float f_1 = 27.12f;
        double d_1 = 2.786;
        System.out.println("Задача 3");
        int classFirst = 23;
        int classSecond = 27;
        int classThird = 30;
        int totalStudents = classFirst + classSecond + classThird;
        int papers = 480;
        int paperForStudent = papers / totalStudents;
        System.out.println("На каждого ученика рассчитано " + paperForStudent + " листов бумаги.");
        System.out.println("Задача 4");
        int speedMachine = 16 / 2;
        int x = 20 * speedMachine;
        int day = 24 * 60 * speedMachine;
        int z = 3 * day * speedMachine;
        int month = 30 * day * speedMachine;
        System.out.println("За 20 минут машина произвела " + x + " штук бутылок");
        System.out.println("За сутки машина произвела " + day + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + z + " штук бутылок");
        System.out.println("За 1 месяц машина произвела " + month + " штук бутылок");
        System.out.println("Задача 5");
        short paintCans = 120;
        byte whitePaint = 2;
        byte redPaint = 4;
        int classrooms = paintCans / (whitePaint + redPaint);
        System.out.println("В школе, где " + classrooms + " классов, нужно " + whitePaint * classrooms + " банок белой краски и " + redPaint * classrooms + " банок коричневой краски");
        System.out.println("Задача 6");
        int bananas = 5 * 80;
        int milk = 200 / 100 * 105;
        int icecream = 2 * 100;
        int eggs = 4 * 700;
        int weightInGramms = bananas + milk + icecream + eggs;
        float weightInKg = weightInGramms / 1000f;
        System.out.println("Масса завтрака в граммах - " + weightInGramms);
        System.out.println("Масса завтрака в кг - "+ weightInKg);
        System.out.println("Задача 7");
        float maxWeightLoss = 7 / 0.5f;
        float minWeightLoss = 7 / 0.25f;
        float averageWeightLoss = 7 / ((0.25f + 0.5f) / 2);
        System.out.println("При максимальном похудении потребуется " + maxWeightLoss + " дней");
        System.out.println("При минимальном похудении потребуется " + minWeightLoss + " дней");
        System.out.println("При среднестатистическом похудении потребуется " + averageWeightLoss + " дней");
        System.out.println("Задача 8");
        int masha = 67760;
        float masha_new = masha * 1.1f;
        int denis = 83690;
        float denis_new = denis * 1.1f;
        int kristina = 76230;
        float kristina_new = kristina * 1.1f;
        System.out.println("Кристина теперь получает " + kristina_new + " рублей. Годовой доход вырос на " + ((kristina_new - kristina) * 12) + "рублей");
        System.out.println("Маша теперь получает " + masha_new + " рублей. Годовой доход вырос на " + (masha_new - masha) * 12 + "рублей");
        System.out.println("Денис теперь получает " + denis_new + " рублей. Годовой доход вырос на " + (denis_new - denis) * 12 + "рублей");
    }
}